//https://fiagwudpgtrlhdlaiize.supabase.co/applications this is the api for this class
import '../models/module.dart';

class Application {
  String? applicationId; // optional, generated by Supabase
  String studentId;

  Module firstModule;
  Module? secondModule;

  bool confirmedEligibility;
  String status;
  DateTime timeOfApplication;

  Application({
    this.applicationId, // leave null when creating new object
    required this.studentId,
    required this.firstModule,
    this.secondModule,
    this.confirmedEligibility = false,
    this.status = "Pending",
    required this.timeOfApplication,
  });
}
