//https://fiagwudpgtrlhdlaiize.supabase.co/students this is the api for the table
class Student {
  String? studentId; // optional, generated by Supabase
  String firstName;
  String lastName;
  String studentNumber;
  String currentYear;

  String? idDocument;
  String? proofOfRegistration;
  String? academicTranscript;
  String? cv;
  String? matricCertificate;

  Student({
    this.studentId, // leave null when creating new object
    required this.firstName,
    required this.lastName,
    required this.studentNumber,
    required this.currentYear,
    this.idDocument,
    this.proofOfRegistration,
    this.academicTranscript,
    this.cv,
    this.matricCertificate,
  });
}
